In [1]:
import pandas as pd
from scipy.stats import ttest_ind, norm

In [2]:
rvs1 =  norm.rvs(loc=5,scale=10,size=500)
rvs1

array([-5.24758529e-01,  1.32976632e+01, -2.93411162e+00, -6.26911779e+00,
       -2.05108725e+00,  5.12749933e+00,  1.29913642e+01,  6.88921743e+00,
        2.40309777e-01,  1.05285650e+01,  6.69681396e+00,  1.53591353e+01,
        5.54605404e+00,  6.81957527e+00,  9.22545045e+00, -5.82122209e+00,
       -4.79256078e+00, -3.03264345e+00,  1.15856178e+01,  3.01717804e-01,
       -8.45632929e-01,  4.50414310e+00, -2.92388983e+00, -2.96027501e+00,
        2.13928085e+01, -3.87473313e+00,  2.91458271e+01, -3.39597504e+00,
        1.83700787e+01,  6.70807040e+00,  9.96912532e+00,  2.68180518e+01,
        1.96131814e+01,  1.34042600e+01,  2.28529441e+01, -3.19603743e+00,
       -5.48168375e+00,  6.57041094e-01,  3.01329668e+00,  1.84046998e+01,
        2.25687494e+01, -9.73575300e+00,  9.08494480e+00,  1.30656611e+01,
       -4.20757175e-01,  2.09542757e+00,  1.12022561e+01,  2.54390412e+01,
        3.91620108e+00,  1.18010037e+01,  6.56954572e+00,  1.29658571e+01,
        1.45836080e+01, -2.66481625e+00,  7.47647238e-01,  2.19189760e+01,
       -1.84400289e+01, -5.59196382e+00, -1.31307048e+01,  1.28154162e+01,
        6.44119656e+00,  5.01389276e+00,  3.15568972e+01,  5.56196347e+00,
        1.62805438e+01,  2.60305017e+01, -6.17559226e+00, -9.51584688e+00,
        5.46074784e+00,  8.56969908e+00,  4.57730947e-01, -1.60211931e+00,
        4.38884467e+00,  1.62660207e+01,  1.59281514e+00, -3.14899678e+00,
        4.84805057e+00,  6.42331557e+00,  8.95565244e+00,  9.91778364e-01,
        4.62966865e+00,  1.29045833e+01,  2.11067681e+01,  1.14649895e+00,
        8.38366112e+00,  1.90377024e+01,  1.14911000e+01,  2.29726284e+01,
        4.12361556e+00,  1.83381298e+00,  4.72874389e+00,  1.34996757e+00,
        4.92666712e+00,  9.75565557e+00,  1.21107166e+01,  2.25552626e+01,
        9.83717538e+00,  7.72996738e+00, -1.11010496e+01,  1.37340024e+01,
       -3.61536135e-01,  8.89101397e+00,  1.44913688e+01,  1.31600421e+01,
       -1.40702460e+01,  4.48191934e+00, -5.59827258e-01,  5.64534682e+00,
        6.09867319e+00, -7.66122730e+00,  2.99303567e+00,  7.30169080e-01,
        8.86941597e+00,  9.40527144e+00, -6.54223141e+00,  1.62114920e+01,
        3.37720178e+00,  1.04878834e+01,  6.85271609e+00,  1.82818193e+00,
       -6.60433049e+00,  1.46059161e+01,  2.23944493e+01,  1.10909440e+01,
        7.55743261e+00,  1.89749035e+01, -8.78277001e+00,  7.04212445e-02,
        1.42534916e+01,  2.17230493e+01,  7.70043654e+00,  7.11400773e+00,
        3.02586882e+01, -1.93940055e+00, -1.21823813e+01,  1.01568177e+01,
        8.73651986e+00,  3.71445674e+00,  1.30403593e+01, -1.12448223e+00,
        1.82381305e-01,  8.86108834e+00,  1.62806023e+01,  1.01014752e+01,
        6.53333340e+00,  7.32273055e+00,  2.21066260e+01,  9.02179162e+00,
        5.67819501e+00,  1.47565791e+01, -7.63271171e-01,  1.93878340e+01,
        5.53666350e+00,  1.55559898e+01, -1.31861536e+01,  7.00647713e+00,
        7.40785585e+00, -1.80866594e+00, -1.36085348e+01,  1.28645823e+01,
       -3.41113171e+00, -2.05884366e+00,  1.23165878e+01,  6.77376221e+00,
        1.38583696e+01,  1.93378160e+00,  2.97484804e+00, -7.42948027e-01,
       -1.32109496e+01,  8.76395046e+00, -5.57268088e+00,  7.00566740e+00,
        3.80089122e+00,  1.07683305e+00,  7.67893321e+00, -2.05937462e+01,
        2.09992060e+01,  4.39408331e+00,  5.37907309e+00,  8.35494577e+00,
       -4.56449378e+00, -7.87837779e+00,  1.33969063e+01, -2.22614968e+00,
       -5.71791391e+00,  1.13382731e+01,  1.03655719e+01,  2.09238157e+01,
        9.20719824e+00, -5.88751434e+00, -8.45934649e+00, -4.97060912e+00,
       -1.97715974e+01, -1.71367023e+01,  1.10260820e+01,  1.26295689e+01,
        3.16507754e+00, -3.10905356e+00,  1.83715133e+01,  1.47762690e+00,
        7.03540123e-01,  6.74808091e+00,  4.48077686e+00,  1.76401854e+00,
        2.15360162e+00, -4.75937839e+00, -3.21554990e+00,  2.94866980e+00,
        1.51151441e+01,  9.78011028e+00,  9.26027473e+00, -9.74214270e+00,
        1.01495797e+01, -1.35666615e+01,  1.47482892e+01,  7.78027551e+00,
        4.07560880e+00, -5.42281440e+00,  1.49809327e+01, -4.03257627e+00,
        8.93504764e+00,  1.23282989e+01,  1.23603797e+01,  2.26055194e+01,
        2.20221417e+01, -2.53286545e+00,  1.90216685e+01,  1.55980652e+01,
       -5.16699261e+00, -8.58904708e+00,  1.04187951e+01,  5.04569152e+00,
       -2.19369447e-01,  8.63216025e+00,  1.31539316e+01, -2.44984651e+01,
        4.84006756e+00,  1.03899665e+01,  4.78020804e+00,  1.11530550e+01,
       -3.03003954e+00, -1.67687042e+00, -1.40620266e+01, -5.41850549e+00,
       -7.48266016e+00, -1.99204107e-01, -4.96463383e+00,  1.12140585e+00,
       -9.68333671e+00,  8.41204587e+00,  6.12027408e+00,  3.09824121e+00,
        1.94426115e+01,  1.30790913e+01,  1.13931685e+01,  1.75524440e+01,
        2.24527852e+01,  2.23887395e+01, -1.64005353e+01,  1.81953116e+01,
        1.12720173e+01, -1.53724869e+00,  9.33308461e+00, -2.71354711e-01,
       -1.52876344e+01,  4.05972763e+00, -8.72228841e+00,  1.38721884e+01,
       -4.57581036e+00, -2.04152305e+00,  2.70508849e+01,  3.43383423e+00,
       -1.84754984e+01, -2.19235228e+00, -4.11606117e-01,  4.32016760e+00,
        2.64723913e+01,  1.32026056e+01,  6.63689347e+00, -1.85789260e+00,
       -8.12412477e+00, -1.01984124e+01,  4.13976130e+00,  7.81163589e-01,
        1.73676571e+01, -1.89321476e+00,  1.09127764e+01, -1.22263130e+00,
        2.65912386e+00, -1.35653066e+00,  6.26435446e+00,  1.06910472e+01,
        3.94897555e+00, -5.80948043e+00,  1.75074753e+01,  3.29189182e+00,
        1.26980185e+01,  1.58384664e+01,  9.19338047e+00,  3.55568361e+00,
       -5.49193642e+00, -5.25496508e+00,  1.81203573e+01,  4.13557422e+00,
        7.76309109e+00,  1.52547306e+00,  2.43545100e+01, -2.56870449e+00,
        2.14414608e+00, -3.59901164e+00,  6.36263237e+00, -8.81653044e-01,
       -2.51690007e+00,  1.67725991e+00, -4.12627270e+00, -6.78696554e-01,
        4.03819584e+00,  1.70474671e+00,  1.57613286e+01,  9.35176046e-01,
        5.72428325e+00,  6.09141220e+00, -3.94985477e+00,  5.73856692e+00,
        7.50633395e+00,  6.55522323e+00,  2.10779214e-01, -1.65547905e+00,
        5.00234208e+00, -1.88522273e-01,  6.33098076e-02, -8.64685515e+00,
        1.12424777e+01, -8.52115776e+00, -2.20092327e-01, -4.78447339e+00,
        1.28862697e+01,  1.62895713e+01, -1.40001308e+00,  7.57853840e-01,
        4.53817162e+00,  9.51653388e+00, -5.06170964e+00, -3.49579621e+00,
        1.01119875e+01, -1.17338629e+01,  6.78886522e+00,  2.02395962e+01,
       -9.57415389e+00,  2.61484078e+01, -5.63633234e+00,  1.24311418e+01,
       -1.03567017e+01, -6.76308281e-01,  1.69020997e+01,  5.51667614e+00,
       -2.28299298e+00,  1.59289328e+01, -6.59750301e+00, -7.61020255e-03,
        1.23464447e+01,  1.05938120e+01, -5.88260044e+00,  1.22940627e+01,
        1.40181584e+01, -3.90278906e+00,  8.76215597e+00,  1.56166694e+01,
        1.13579516e+01,  7.86300041e+00,  7.97064055e+00,  7.90697000e+00,
       -2.11247639e+01,  7.57518582e+00, -1.62382285e+01,  1.55765240e+01,
       -1.54131951e+00, -7.78302272e+00,  1.12136968e+01,  2.17783162e+00,
        9.53395879e-01,  1.70219639e+01,  3.81796714e+00,  6.63413560e+00,
        1.76951935e+01,  3.96145714e+00,  1.77930142e+01,  6.83867999e+00,
       -1.59341116e+01,  2.05255875e+01,  9.24987279e+00,  5.26735840e+00,
        1.59500512e+01,  2.20952538e+01, -9.74588871e+00, -4.35479698e+00,
        6.42422093e+00,  1.93870955e+00,  1.27426951e+01,  1.10428451e+01,
        5.13386628e+00,  2.07643148e+01,  4.88180003e+00,  3.24556471e+00,
       -6.16968880e+00,  5.13917431e+00,  4.74508809e+00,  2.84128436e-01,
        1.33286001e+01,  2.10653026e+01,  1.70342886e+01, -4.83023693e+00,
        1.35097184e+01,  2.56147538e+01, -5.15095013e+00, -4.70324070e+00,
       -7.37685267e+00,  1.39419800e+01,  1.80497853e+01, -8.19214423e+00,
        1.96341702e+01,  1.17555942e+00,  3.64252461e-01,  9.74047965e+00,
        4.22997755e+00,  1.29742515e+01,  4.47399472e+00,  2.60383200e+01,
        1.10079373e+00,  4.33415110e+00,  8.03757584e+00,  1.55239567e+01,
        1.03649758e+01,  8.06187607e+00,  1.69158712e+01,  4.93626171e+00,
        1.53794636e+01,  9.52287861e+00, -2.03823492e+00, -1.40996231e+00,
       -3.70626872e-01,  9.87512368e+00, -8.39006181e+00,  9.48381298e+00,
        1.21452336e+01,  2.19236664e+01,  6.21026193e+00,  3.07288280e+01,
       -3.09351142e+00,  6.34457650e+00,  6.82015612e+00,  8.92643810e+00,
        4.03018129e+00,  1.14174619e+01,  1.05045588e+01,  4.72077823e+00,
       -5.96946221e+00,  2.33280453e-01,  5.81413779e+00, -7.99734808e+00,
        1.08532094e+01,  1.44257444e+01, -1.52730700e+00,  1.94831292e+01,
        6.99019863e+00, -1.27343910e+00, -2.24848682e+00,  1.25363182e+01,
        9.77424187e+00, -4.78682386e+00,  3.76164681e-02, -3.42169605e+00,
       -1.33242875e+01,  1.26114120e+01, -1.15318307e+01, -1.56011319e+01,
        4.05516251e+00, -1.19667249e+01,  1.99870448e-01,  1.13270188e+01,
       -8.44448242e+00,  6.63097313e-02, -1.78169338e+01, -1.18342185e+01,
       -3.01962629e+00, -2.04126108e+00,  1.14434137e+01,  1.11944796e+01,
        9.38877063e+00,  1.78675128e+01,  2.25922920e+01, -1.88791398e+00,
        1.16375431e+01,  2.74216937e+01,  9.52343396e+00, -2.15653684e-01,
        3.49876665e+00,  2.13283774e+00,  1.84994233e+01,  6.27439854e+00])

In [3]:
rvs2 =  norm.rvs(loc=5,scale=10,size=1000)
ttest_ind(rvs1, rvs2)

Ttest_indResult(statistic=-0.2040904614531211, pvalue=0.838310530586387)

In [4]:
df = pd.read_csv('Part1_Crime_2017_to_2018.csv')

In [5]:
df.shape

(100677, 19)

In [6]:
df.dtypes

objectid             int64
rowid_               int64
crimedatetime       object
crimetime           object
crimecode           object
location            object
description         object
inside_outside      object
weapon              object
post               float64
district            object
neighborhood        object
latitude           float64
longitude          float64
geolocation         object
premise             object
vriname             object
total_incidents      int64
hashedrecord        object
dtype: object

In [7]:
df['crimedatetime'] = pd.to_datetime(df['crimedatetime'])

In [8]:
df.head(3).T

,0,1,2
objectid,1,2,3
rowid_,82567,82568,82569
crimedatetime,2018-12-31 04:36:00,2018-12-31 17:30:00,2018-12-31 11:10:00
crimetime,4:36:00,17:30:00,11:10:00
crimecode,6G,6D,4E
location,400 W LEXINGTON ST,400 E 25TH ST,4200 FAIRFAX RD
description,LARCENY,LARCENY FROM AUTO,COMMON ASSAULT
inside_outside,I,O,I
weapon,NaN,NaN,NaN
post,114,513,624
district,CENTRAL,NORTHERN,NORTHWEST
neighborhood,DOWNTOWN,HARWOOD,WEST FOREST PARK
latitude,39.2916,39.3181,39.3204
longitude,-76.6211,-76.611,-76.6877
geolocation,"(39.2916,-76.6211)","(39.3181,-76.611)","(39.3204,-76.6877)"
premise,SPECIALTY STORE,STREET,APT/CONDO - OCCUPIED
vriname,NaN,NaN,NaN
total_incidents,1,1,1
hashedrecord,0xC961940C8A250EDAFFBB5E3D0E48727AC79817AE9EA6...,0x46FADA38EAC4E24AA9CCD81259651137A8073440F5F2...,0xFE7A5EDB382D00C6265CB48762D75AB7D2BC374871E8...

There is no significant difference between crimes inside and outsides

In [9]:
df['inside_outside'].value_counts()

O          40115
I          38355
Outside     1854
Inside       176
Name: inside_outside, dtype: int64

In [10]:
df['inside'] =  [1 if i=='I' else 0 for i in df['inside_outside']]
df['outside'] = [1 if i=='O' else 0 for i in df['inside_outside']]

In [11]:
df.head()

,objectid,rowid_,crimedatetime,crimetime,crimecode,location,description,inside_outside,weapon,post,...,neighborhood,latitude,longitude,geolocation,premise,vriname,total_incidents,hashedrecord,inside,outside
0,1,82567,2018-12-31 04:36:00,4:36:00,6G,400 W LEXINGTON ST,LARCENY,I,NaN,114.0,...,DOWNTOWN,39.2916,-76.6211,"(39.2916,-76.6211)",SPECIALTY STORE,NaN,1,0xC961940C8A250EDAFFBB5E3D0E48727AC79817AE9EA6...,1,0
1,2,82568,2018-12-31 17:30:00,17:30:00,6D,400 E 25TH ST,LARCENY FROM AUTO,O,NaN,513.0,...,HARWOOD,39.3181,-76.6110,"(39.3181,-76.611)",STREET,NaN,1,0x46FADA38EAC4E24AA9CCD81259651137A8073440F5F2...,0,1
2,3,82569,2018-12-31 11:10:00,11:10:00,4E,4200 FAIRFAX RD,COMMON ASSAULT,I,NaN,624.0,...,WEST FOREST PARK,39.3204,-76.6877,"(39.3204,-76.6877)",APT/CONDO - OCCUPIED,NaN,1,0xFE7A5EDB382D00C6265CB48762D75AB7D2BC374871E8...,1,0
3,4,82570,2018-12-31 19:45:00,19:45:00,4E,6500 SAINT HELENA AVE,COMMON ASSAULT,I,NaN,234.0,...,SAINT HELENA,39.2600,-76.5311,"(39.26,-76.5311)",ROW/TOWNHOUSE-OCC,NaN,1,0xD60C2FB5283D72C29328A7DF528251D4B0F3EF0D9474...,1,0
4,5,82571,2018-12-31 22:43:00,22:43:00,4A,2400 W BELVEDERE AVE,AGG. ASSAULT,I,FIREARM,532.0,...,LEVINDALE,39.3545,-76.6623,"(39.3545,-76.6623)",HOSP/NURS. HOME,NaN,1,0x3D27E5CF73522B733BA7EA512013FE1D8BE621801CC8...,1,0

In [12]:
df_io = df[['inside', 'outside']].groupby(df['crimedatetime'].dt.date).sum() # this may be count if you are counting
df_io

               inside  outside
crimedatetime
2017-01-01         66       58
2017-01-02         51       66
2017-01-03         40       35
2017-01-04         18       14
2017-01-05         17       20
...               ...      ...
2018-12-27         43       52
2018-12-28         57       65
2018-12-29         47       60
2018-12-30         48       57
2018-12-31         50       68

[730 rows x 2 columns]

In [13]:
inside = df_io['inside']
outside = df_io['outside']  
ttest_ind(inside, outside , equal_var=False)

Ttest_indResult(statistic=-3.515854699741415, pvalue=0.0004519468095047608)

pvalue is less than 0.05

Let's do another example.

Assumption: There is no significant different between Hampden & Canton neighborhood in terms of weapon used crimes.

In [ ]:
df['weapon'].value_counts()

In [15]:
df_weapon = df[df['weapon'].isna() == False]

In [16]:
hampden = df_weapon[ df_weapon['neighborhood'] == 'HAMPDEN' ]
canton = df_weapon[ df_weapon['neighborhood'] == 'CANTON' ]

In [17]:
hampden_counts = hampden['weapon'].groupby( hampden['crimedatetime'].dt.date ).count()
# hampden_counts

In [18]:
canton_counts = canton['weapon'].groupby( canton['crimedatetime'].dt.date ).count()
# canton_counts

In [19]:
ttest_ind(hampden_counts, canton_counts, equal_var=False)

Ttest_indResult(statistic=0.1379880975095151, pvalue=0.8904029753837779)